/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
<<<<<<< HEAD
    "aws_project_region": "us-east-1"
=======
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "OwnerAPI",
            "endpoint": "https://1e9x45pikj.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "PropertyAPI",
            "endpoint": "https://wu9cyiffi2.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
>>>>>>> e9d38501badbd20923c91421f225dfa28d279aaf
};


export default awsmobile;
